import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { browserLocalPersistence, getAuth, GoogleAuthProvider, onAuthStateChanged, setPersistence, signInWithPopup, signOut } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { addDoc, collection, deleteDoc, doc, getDocs, getFirestore, limit, orderBy, query, serverTimestamp, setDoc, where } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDUOiBJMfjHyFISy_U7rA7ldKKnoZ05QvQ',authDomain:'custom-figures-collector.firebaseapp.com',projectId:'custom-figures-collector',storageBucket:'custom-figures-collector.firebasestorage.app',messagingSenderId:'725550496124',appId:'1:725550496124:web:6e2910da4ee2f60bcc8cf9'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=selector=>document.querySelector(selector),authButton=$('#authButton'),authStatus=$('#authStatus'),workspace=$('#adminWorkspace'),accessPanel=$('#accessPanel'),form=$('#premiumForm'),formStatus=$('#formStatus'),tbody=$('#premiumUsers'),auditEntries=$('#auditEntries');
let users=[],globalReleases=[];
const setStatus=(element,message,error=false)=>{element.textContent=message;element.classList.toggle('error',error)};
const displayDate=value=>{const date=value?.toDate?.()||value;if(!date)return'—';return new Date(date).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})};
const releaseDate=value=>value?.toDate?.()||new Date(value);
const normalizeUrl=value=>{const text=String(value||'').trim();if(!text)return'';const candidate=/^[a-z][a-z\d+.-]*:\/\//i.test(text)?text:`https://${text}`;let url;try{url=new URL(candidate)}catch{throw Error('Enter a valid website URL.')}if(!['http:','https:'].includes(url.protocol)||!url.hostname)throw Error('Enter an HTTP or HTTPS website URL.');return url.href};
const localTimeZone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',timeZones=[...new Set(['UTC',...(typeof Intl.supportedValuesOf==='function'?Intl.supportedValuesOf('timeZone'):['Europe/Lisbon','Europe/London','Europe/Paris','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','Asia/Tokyo','Australia/Sydney'])])];
const timeZoneLabel=zone=>{try{const abbreviation=new Intl.DateTimeFormat('en-GB',{timeZone:zone,timeZoneName:'short'}).formatToParts(new Date()).find(part=>part.type==='timeZoneName')?.value;return `${zone.replaceAll('_',' ')} (${abbreviation||zone})`}catch{return zone.replaceAll('_',' ')}};
$('#globalReleaseZone').replaceChildren(...timeZones.map(zone=>new Option(timeZoneLabel(zone),zone)));
$('#globalReleaseUrl').addEventListener('blur',event=>{try{event.target.value=normalizeUrl(event.target.value)}catch{}});
function renderUsers(){const search=$('#userSearch').value.trim().toLowerCase(),visible=users.filter(user=>!search||user.email.toLowerCase().includes(search));tbody.replaceChildren(...visible.map(user=>{const row=document.createElement('tr');row.innerHTML=`<td>${user.email}</td><td><span class="status ${user.status}">${user.status}</span></td><td>${user.licenseType}</td><td>${displayDate(user.updatedAt)}</td><td><button type="button" class="edit-user">Edit</button></td>`;row.querySelector('button').onclick=()=>{$('#premiumEmail').value=user.email;$('#premiumStatus').value=user.status;$('#premiumNotes').value=user.notes||'';scrollTo({top:document.querySelector('.editor').offsetTop-20,behavior:'smooth'})};return row}));$('#emptyUsers').hidden=visible.length>0;$('#premiumCount').textContent=users.length;$('#activeCount').textContent=users.filter(user=>user.status==='active').length;$('#inactiveCount').textContent=users.filter(user=>user.status!=='active').length}
function renderAudit(entries=[]){auditEntries.replaceChildren(...entries.map(entry=>{const item=document.createElement('article');item.className='audit-entry';item.innerHTML=`<time>${displayDate(entry.createdAt)}</time><span><strong>${entry.action.replaceAll('-',' ')}</strong><br><small>${entry.targetEmail||entry.targetUid}</small></span><small>${entry.administratorEmail||entry.administratorUid}</small>`;return item}));if(!entries.length)auditEntries.textContent='No administrative changes yet.'}
function clearGlobalRelease(){const releaseForm=$('#globalReleaseForm');releaseForm.reset();$('#globalReleaseId').value='';$('#globalReleaseZone').value=localTimeZone;$('#globalReleaseStatus').textContent='';$('#saveGlobalRelease').textContent='Publish drop'}
function editGlobalRelease(release){clearGlobalRelease();$('#globalReleaseId').value=release.id;$('#globalReleaseName').value=release.name||'';$('#globalReleaseSite').value=release.siteName||'';$('#globalReleaseUrl').value=release.siteUrl||'';$('#globalReleaseNotes').value=release.notes||'';$('#globalReleaseZone').value=release.timeZone||localTimeZone;const date=releaseDate(release.startsAt);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());$('#globalReleaseTime').value=date.toISOString().slice(0,16);$('#globalReleaseTime').dispatchEvent(new Event('input',{bubbles:true}));$('#saveGlobalRelease').textContent='Update drop';document.querySelector('.release-admin-editor').scrollIntoView({behavior:'smooth'})}
function renderGlobalReleases(){const container=$('#globalReleaseList');container.replaceChildren(...globalReleases.map(release=>{const item=document.createElement('article');item.className='global-release-item';const time=document.createElement('time');time.textContent=displayDate(release.startsAt);const copy=document.createElement('div'),title=document.createElement('h3'),site=document.createElement('small');title.textContent=release.name;site.textContent=release.siteName||release.siteUrl||'No website';copy.append(title,site);const actions=document.createElement('div');actions.className='global-release-item-actions';const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.onclick=()=>editGlobalRelease(release);const remove=document.createElement('button');remove.type='button';remove.textContent='Delete';remove.onclick=async()=>{if(!confirm(`Delete “${release.name}”?`))return;await deleteDoc(doc(db,'releaseEvents',release.id));await loadData()};actions.append(edit,remove);item.append(time,copy,actions);return item}));$('#emptyGlobalReleases').hidden=globalReleases.length>0}
async function loadData(){const [entitlements,audit,releases]=await Promise.all([getDocs(query(collection(db,'premiumEntitlements'),orderBy('updatedAt','desc'))),getDocs(query(collection(db,'premiumAuditLog'),orderBy('createdAt','desc'),limit(100))),getDocs(query(collection(db,'releaseEvents'),orderBy('startsAt','asc')))]);users=entitlements.docs.map(item=>({uid:item.id,...item.data()}));globalReleases=releases.docs.map(item=>({id:item.id,...item.data()}));renderUsers();renderAudit(audit.docs.map(item=>({id:item.id,...item.data()})));renderGlobalReleases()}
async function authorize(user){authButton.textContent='Sign out';setStatus(authStatus,`Checking administrator access for ${user.email}…`);try{if(user.uid!=='rh8WrITlLTXrsDj5mbJHzA1D4Bk2')throw Error('Administrator access was not granted.');accessPanel.hidden=true;workspace.hidden=false;await loadData()}catch(error){workspace.hidden=true;accessPanel.hidden=false;setStatus(authStatus,error.message||'Administrator access was denied.',true)}}
authButton.onclick=async()=>{try{if(auth.currentUser){await signOut(auth);return}await signInWithPopup(auth,provider)}catch(error){setStatus(authStatus,error.message,true)}};
form.onsubmit=async event=>{event.preventDefault();const button=$('#savePremium'),email=$('#premiumEmail').value.trim().toLowerCase(),status=$('#premiumStatus').value,notes=$('#premiumNotes').value.trim();button.disabled=true;setStatus(formStatus,'Saving…');try{const profiles=await getDocs(query(collection(db,'premiumProfiles'),where('email','==',email),limit(1)));if(profiles.empty)throw Error('This customer must sign in once before premium access can be granted.');const profile=profiles.docs[0],administrator=auth.currentUser;await setDoc(doc(db,'premiumEntitlements',profile.id),{email,tier:'premium',status,licenseType:'lifetime',notes,updatedAt:serverTimestamp(),updatedBy:administrator.uid},{merge:true});await addDoc(collection(db,'premiumAuditLog'),{action:'set-entitlement',targetUid:profile.id,targetEmail:email,administratorUid:administrator.uid,administratorEmail:administrator.email||'',status,createdAt:serverTimestamp()});setStatus(formStatus,`${email} updated.`);form.reset();await loadData()}catch(error){setStatus(formStatus,error.message,true)}finally{button.disabled=false}};
$('#globalReleaseForm').onsubmit=async event=>{event.preventDefault();const button=$('#saveGlobalRelease'),id=$('#globalReleaseId').value.trim(),startsAt=new Date($('#globalReleaseTime').value);button.disabled=true;setStatus($('#globalReleaseStatus'),'Saving…');try{if(Number.isNaN(startsAt.getTime()))throw Error('Enter a valid date and time.');const siteUrl=normalizeUrl($('#globalReleaseUrl').value);const data={name:$('#globalReleaseName').value.trim(),siteName:$('#globalReleaseSite').value.trim(),siteUrl,startsAt,timeZone:$('#globalReleaseZone').value,notes:$('#globalReleaseNotes').value.trim(),updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid};if(id)await setDoc(doc(db,'releaseEvents',id),data,{merge:true});else await addDoc(collection(db,'releaseEvents'),{...data,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});clearGlobalRelease();setStatus($('#globalReleaseStatus'),'Release published.');await loadData()}catch(error){setStatus($('#globalReleaseStatus'),error.message,true)}finally{button.disabled=false}};
$('#cancelGlobalRelease').onclick=clearGlobalRelease;$('#userSearch').oninput=renderUsers;$('#refreshData').onclick=()=>loadData().catch(error=>setStatus(authStatus,error.message,true));clearGlobalRelease();
await setPersistence(auth,browserLocalPersistence);onAuthStateChanged(auth,user=>{if(user)authorize(user);else{authButton.textContent='Sign in';workspace.hidden=true;accessPanel.hidden=false;setStatus(authStatus,'Sign in with the administrator account.')}});
